const POSTS = [
  'redis/Redis.md',
  'redis/LuaScript.md',
  'server/OAuth2와_OIDC.md',
  'server/CQRS.md',
  'server/vertx.md',
  'Spring/WebFlux.md',
  'Spring/Spring AOP.md',
  'Spring/Spring Batch.md',
  'Spring/IoC와_DI.md',
  'Spring/TransactionalEventListener.md',
  'Spring/Filter와 Interceptor.md',
  'Spring/Spring의 전역 예외 커스텀.md',
  'Spring/Circuit_Breaker.md',
  'Spring/Spring에서 Redis를 이용한 캐싱 방법.md',
  'Spring/Spring HTTP Interface.md',
  'Kafka/Kafka란?.md',
  'Kafka/Kafka Broker.md',
  'Kafka/Kafka Producer.md',
  'Kafka/Kafka Consumer.md',
  'Kafka/Apache Avro.md',
  'Kafka/스키마 레지스트리.md',
  'Kafka/Spring Bean.md',
  'Kafka/Spring의 Kafka 환경 구축.md',
  'Kafka/Local-postgreSQL 환경에서 CDC 구축하기.md',
  'Design-Pattern/CQRS.md',
  'Design-Pattern/SAGA_Pattern.md',
  'Design-Pattern/Outbox_Pattern.md',
  'Design-Pattern/Entity,VO,DTO.md',
  'Markdown/Mermaid-Flowchart문법.md',
  'Markdown/Mermaid-Sequence_Diagram문법.md',
  'Markdown/Mermaid-ERDiagram문법.md',
  'development_tools/Mac 개발 환경 세팅 가이드.md'
];
